---
- hosts: localhost
  strategy: linear
  connection: local
  debugger: on_failed
  vars_files:
    - config.yaml
  roles:
    - name: git
      tags: git

    - name: ssh
      tags: ssh

    - name: homebrew
      tags: homebrew
      when: ansible_facts["os_family"] == 'Darwin'

    - name: scripts
      tags: scripts

    - name: system
      tags: system
      when: ansible_facts["os_family"] == 'Darwin'

    - name: window-management
      tags: window-management
      when: ansible_facts["os_family"] == 'Darwin'

    - name: kitty
      tags: kitty
      when: ansible_facts["os_family"] == 'Darwin'

    - name: wezterm
      tags: wezterm

    - name: zsh
      tags: zsh

    - name: tmux
      tags: tmux

    - name: neovim
      tags: neovim
