---
- name: "Ensure tmux is installed"
  community.general.homebrew:
    name: tmux
    options: "HEAD"
    state: present

- name: "Ensure Tmux Plugin Manager is present in {{ tpm_local_path }}"
  ansible.builtin.file:
    path: "{{ tpm_local_path }}"
    recurse: true
    state: directory
    owner: "{{ ansible_user }}"
  register: is_tpm_installed
  become: true

- name: "Ensure Tmux Plugin Manager is cloned"
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ tpm_local_path }}"
    version: "master"
    update: false
  when: is_tpm_installed.stat.isdir is not defined or not is_tpm_installed.stat.isdir

- name: "Ensure tmux config is linked"
  ansible.builtin.file:
    src: "{{ tmux_config.src }}"
    dest: "{{ tmux_config.dest }}"
    force: true
    state: link
  become: true

- name: "Source tmux config"
  ansible.builtin.command: 'tmux source {{ tmux_config.dest }}'
  changed_when: false

- name: "Install tmux plugins"
  ansible.builtin.command: 'sh {{ tpm_local_path }}/scripts/install_plugins.sh'
  changed_when: false
