#! /usr/bin/env zsh

yabai -m config layout bsp
yabai -m config split_type auto
yabai -m config auto_balance off
yabai -m config top_padding 4
yabai -m config bottom_padding 4
yabai -m config right_padding 4
yabai -m config left_padding 4
yabai -m config window_gap 4
yabai -m config window_border_blur off
yabai -m config window_border on
yabai -m config window_border_width 2
yabai -m config window_border_radius 10
yabai -m config mouse_follows_focus on
yabai -m config window_placement second_child
yabai -m config mouse_modifier fn

yabai -m config active_window_border_color 0xFFF38BA8
yabai -m config normal_window_border_color 0x00FFFFFF

yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add app="^Brave Browser$" title="^Picture in Picture$" manage=off
yabai -m rule --add app="^Google Chrome$" title="^Picture in Picture$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add title='^Slack \| mini panel$' manage=off layer=above border=off

yabai -m signal --add event=space_changed action="$HOME/.config/yabai/scripts/yabai_borders.sh"

yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
