---
- name: "Ensure neovim is installed"
  community.general.homebrew:
    name: neovim
    options: "HEAD"
    state: latest
  when: ansible_facts['os_family'] == 'Darwin'

- name: "Ensure neovim folder exists at {{ neovim.dest }}"
  ansible.builtin.file:
    path: "{{ neovim.dest }}"
    recurse: true
    state: directory
    owner: "{{ ansible_user }}"

- name: "Ensure config is linked to {{ neovim.dest }}"
  ansible.builtin.file:
    src: "{{ neovim.src }}"
    dest: "{{ neovim.dest }}"
    force: true
    state: link
